name: deploy

inputs:
  ARTIFECTS_REGISTRY: 
    required: true
  HELM_VERSION:
    required: true
  MS_NAME:
    required: true
  VALUE_FILE_PATH:
    required: true
  NAMESPACE:
    required: true
  SERVICE_PORT:
    required: true
  AUTOSCALING:
    required: true
  REPLICACOUNT:
    required: true
  BRANCH_NAME:
    required: true
  GCP_SERVICE_ACCOUNT_KEY:
    required: true
  

runs:
  using: "composite"
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Authenticate to Google Cloud
    id: auth
    uses: google-github-actions/auth@v1
    with:
      credentials_json: ${{ inputs.GCP_SERVICE_ACCOUNT_KEY }}

  - name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@v1
    with:
      version: 'latest'
  - name: Install gke-gcloud-auth-plugin
    shell: bash
    run: |
      gcloud components install gke-gcloud-auth-plugin
      gcloud components update

  - name: Configure kubectl
    shell: bash
    run: |
      gcloud container clusters get-credentials iot-cluster-01 --zone us-central1 --project iotapp-427320

  - name: Set up Helm
    uses: azure/setup-helm@v3

  - name: Deploy Helm chart
    shell: bash
    run: |
      helm upgrade --install test_release ./Deploy/helm-template/iot --namespace default