name: build_validation

inputs:
  SONAR_TOKEN:
    required: true
  PROJECT_FOLDER:
    required: true
  PROJECT_KEY:
    required: true
  PROJECT_ORGANIZATION:
    required: true

runs:
  using: "composite"
  steps:
      # Checks out the repository this file is in
    - uses: actions/checkout@v3

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: ${{ inputs.PROJECT_FOLDER }}
        args: >
          -Dsonar.organization=${{ inputs.PROJECT_KEY }}
          -Dsonar.projectKey=${{ inputs.PROJECT_ORGANIZATION }}
      env:
        # GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}