name: sub-node 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - uat2
      - qa
      - dev
    paths:
      - Src/node/**
      - .github/workflows/sub-node.yml
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]
    paths:
      - Src/sub-node/**
      - .github/workflows/sub-node.yml

env:
  ARTIFECTS_REGISTRY: "us-central1-docker.pkg.dev/iotapp-427320/iot-app-registry"
  CONTAINER_NAME: "sub-node"
  CHART_PATH: "Deploy/helm-template/iot"
  FOLDER_PATH: "Src/node"
  PROJECT_KEY: "iot-app_iot-app"
  PROJECT_ORGANIZATION: "iot-app"
  MS_NAME: "sub-node"
  HELM_VERSION: "0.1.1"
  VALUE_FILE_PATH: "Deploy/helm-values/sub-node.yaml"
  CONFIG_FILE: "kube.config"
  SERVICE_PORT: 80
  AUTOSCALING: false
  REPLICACOUNT: 1
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  scancode:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'dev'
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: build
        uses: "./.github/template/build_validation"
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_FOLDER: ${{ env.FOLDER_PATH }}
          PROJECT_KEY: ${{ env.PROJECT_KEY }}
          PROJECT_ORGANIZATION: ${{ env.PROJECT_ORGANIZATION }}
          

  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/main'
    environment: ${{ github.ref == 'refs/heads/dev' && 'DEV' || github.ref == 'refs/heads/qa' && 'QA' || github.ref == 'refs/heads/main' && 'PROD'  }}
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: build
        uses: "./.github/template/build"
        with:
          FOLDER_PATH: ${{ env.FOLDER_PATH }} 
          ARTIFECTS_REGISTRY: ${{ env.ARTIFECTS_REGISTRY }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          CHART_PATH: ${{ env.CHART_PATH }}
          HELM_VERSION: ${{ env.HELM_VERSION }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}

  # deploy_helm:
  #   permissions:
  #     actions: read
  #     contents: read
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master'
  #   environment: ${{ github.ref == 'refs/heads/release' && 'QA' || github.ref == 'refs/heads/staging' && 'UAT' || github.ref == 'refs/heads/master' && 'PROD'  }}
  #   needs: [buildImage]
  #   steps:
  #     # Checks out the repository this file is in
  #     - uses: actions/checkout@v3
  #     - name: deploy
  #       uses: "./.github/template/deploy"
  #       with:
  #         AZURE_CONTAINER_REGISTRY: ${{ env.AZURE_CONTAINER_REGISTRY }} 
  #         HELM_VERSION: ${{ env.HELM_VERSION }}
  #         MS_NAME: ${{ env.MS_NAME }}
  #         VALUE_FILE_PATH: ${{ env.VALUE_FILE_PATH }}
  #         CONFIG_FILE: ${{ env.CONFIG_FILE }}
  #         GRPC: ${{ env.GRPC }}
  #         GRPC_PORT: ${{ env.GRPC_PORT }}
  #         SERVICE_PORT: ${{ env.SERVICE_PORT }}
  #         AUTOSCALING: ${{ env.AUTOSCALING }}
  #         REPLICACOUNT: ${{ env.REPLICACOUNT }}
  #         NAMESPACE: ${{ vars.NAMESPACE }}
  #         ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  #         ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  #         K8s_CONFIG_FILE: ${{ secrets.ACR_CONFIG_FILE }}
  #         BRANCH_NAME: ${{ env.BRANCH_NAME }} 


      


